### ISSUE TITLE
bro-gen is not compatible with ffi-clang v0.10.0 due breaking changes in API

### ISSUE THREAD

**Issue by dkimitsa** [dkimitsa/robovm-bro-gen#4]
https://github.com/ioquatix/ffi-clang/issues/82

```
/Users/roman/Downloads/bindings/robovm-bro-gen/bro-gen.rb:2911:in `process': undefined method `visit_children' for an instance of FFI::Clang::Cursor (NoMethodError)

            cursor.visit_children do |cursor, _parent|
                  ^^^^^^^^^^^^^^^
	from /Users/roman/Downloads/bindings/robovm-bro-gen/bro-gen.rb:3974:in `block in <main>'
	from /Users/roman/Downloads/bindings/robovm-bro-gen/bro-gen.rb:3816:in `each'
	from /Users/roman/Downloads/bindings/robovm-bro-gen/bro-gen.rb:3816:in `<main>'
```

**Comment by dkimitsa** [comment]
fixed with https://github.com/dkimitsa/robovm-bro-gen/commit/f8f9c67cecd474e746e5de3f85ecf893ae39b535
